print('Welcome to Startup Name Generator 🚀')
product_animal = input('❓ If your product was an animal what would it be?\n🐶 ')
product = input ("❓ Describe your product in one word: \n👉 ")
print("📢 Here's your disruptively faboulus name")
print("🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥")
print(product_animal + product)
print("🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥")
print('😎')
